import React from "react";
import "./Conclusion.css";

function Conclusion({ result }) {
  if (!result) return null;

  const plagiarism = result?.Plagiarism_and_Fact_Checking?.Plagiarism;
  const nliCheck = result?.Plagiarism_and_Fact_Checking?.NLI_Check;
  const factCheck = result?.Plagiarism_and_Fact_Checking?.Fact_Check || [];
  const localBias = result?.Bias_Detection?.Local_Model || {};
  const geminiBias = result?.Bias_Detection?.Gemini_Model || {};
  // --- CORRECTED: Use the correct key from the API response ---
  const generation = result?.AI_Generated_Content_Detection || {};

  // --- Risk Mapping Functions ---
  const getPlagiarismRisk = () => {
    if (plagiarism?.Verdict === "Possibly Paraphrased") return "Medium";
    return "Low";
  };

  const getFactCheckRisk = () => {
    if (factCheck.length === 0) return "High"; // No claims at all
    const allNotFound = factCheck.every((c) => c.Rating === "Not Found");
    if (allNotFound) return "Medium";
    return "Low";
  };

  const getNLIRisk = () => {
    if (!nliCheck?.Label) return "Unknown";

    if (nliCheck.Label === "Contradiction" && nliCheck.Confidence >= 0.5)
      return "High";
    if (nliCheck.Label === "Entailment" && nliCheck.Confidence >= 0.5)
      return "Low";
    return "Medium"; // Neutral or low confidence
  };

  const getBiasRisk = () => {
    return localBias?.Bias !== "Not-detected" ||
      geminiBias?.Bias !== "Not-detected"
      ? "Medium"
      : "Low";
  };

  // --- CORRECTED: Check for the correct label value ---
  const getAIRisk = () => {
    return generation?.Predicted_Label === "AI-Generated" ? "Medium" : "Low";
  };

  // --- Narrative ---
  let narrative = `The analyzed text `;
  if (getPlagiarismRisk() === "Medium")
    narrative += "appears to be paraphrased from external sources. ";
  if (getFactCheckRisk() === "High")
    narrative +=
      "lacks verified fact-check references entirely, reducing reliability. ";
  else if (getFactCheckRisk() === "Medium")
    narrative +=
      "claims were extracted but none were verified, suggesting missing evidence. ";
  if (getNLIRisk() === "Medium")
    narrative +=
      "consistency analysis is inconclusive, with some uncertainty in alignment. ";
  if (getNLIRisk() === "High")
    narrative += "some contradictions detected, which lowers consistency. ";
  if (getBiasRisk() === "Medium")
    narrative +=
      "there are signs of biased or loaded language that may shape perception. ";
  if (getAIRisk() === "Medium")
    narrative +=
      "it may have been generated by AI, raising questions of authorship. ";
  if (
    getPlagiarismRisk() === "Low" &&
    getFactCheckRisk() === "Low" &&
    getNLIRisk() === "Low" &&
    getBiasRisk() === "Low" &&
    getAIRisk() === "Low"
  ) {
    narrative =
      "appears consistent, unbiased, factually supported, and likely human-written.";
  }

  return (
    <div className="conclusion-card">
      <h2 className="conclusion-title">★ Overall Conclusion</h2>

      {/* Scorecard */}
      <table className="scorecard">
        <thead>
          <tr>
            <th>Module</th>
            <th>Result</th>
            <th>Risk</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Plagiarism</td>
            <td>{plagiarism?.Verdict || "Unknown"}</td>
            <td>{getPlagiarismRisk()}</td>
          </tr>
          <tr>
            <td>Fact Check</td>
            <td>
              {factCheck.length === 0
                ? "No claims detected"
                : factCheck.every((c) => c.Rating === "Not Found")
                ? "Claims extracted but none verified"
                : "Some claims verified"}
            </td>
            <td>{getFactCheckRisk()}</td>
          </tr>
          <tr>
            <td>NLI Consistency</td>
            <td>
              {nliCheck?.Label || "Unknown"} (conf:{" "}
              {nliCheck?.Confidence?.toFixed(2) || 0})
            </td>
            <td>{getNLIRisk()}</td>
          </tr>
          <tr>
            <td>Bias Detection</td>
            <td>{getBiasRisk() === "Low" ? "No major bias" : "Bias indicators present"}</td>
            <td>{getBiasRisk()}</td>
          </tr>
          {/* --- CORRECTED: Display the correct data fields --- */}
          <tr>
            <td>AI/Human</td>
            <td>
                {generation?.Predicted_Label || "Pending"}
                {generation?.Confidence && ` (conf: ${generation.Confidence}%)`}
            </td>
            <td>{getAIRisk()}</td>
          </tr>
        </tbody>
      </table>

      {/* Narrative */}
      <div className="narrative">
        <p>{narrative}</p>
      </div>
    </div>
  );
}

export default Conclusion;
